-- MySQL Script generated by MySQL Workbench
-- Sat Jun 26 15:38:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema leaguetracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leaguetracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leaguetracker` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `leaguetracker` ;

-- -----------------------------------------------------
-- Table `leaguetracker`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`family` (
  `familyID` INT NOT NULL AUTO_INCREMENT,
  `contact1FirstName` VARCHAR(45) NULL,
  `contact1LastName` VARCHAR(45) NULL,
  `contact2FirstName` VARCHAR(45) NULL,
  `contact2LastName` VARCHAR(45) NULL,
  `addressLine1` VARCHAR(45) NULL,
  `addressLine2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipCode` VARCHAR(45) NULL,
  `PrimaryPhone` INT(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`familyID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leaguetracker`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`division` (
  `divisionID` INT NOT NULL AUTO_INCREMENT,
  `divisionName` VARCHAR(45) NULL,
  `startAgeDOB` DATE NULL,
  `endAgeDOB` DATE NULL,
  `cost` INT NULL,
  PRIMARY KEY (`divisionID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leaguetracker`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`team` (
  `teamID` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(45) NULL,
  `divisionID` INT NOT NULL,
  PRIMARY KEY (`teamID`, `divisionID`),
  CONSTRAINT `fk_team_division1`
    FOREIGN KEY (`divisionID`)
    REFERENCES `leaguetracker`.`division` (`divisionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_team_division1_idx` ON `leaguetracker`.`team` (`divisionID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leaguetracker`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`player` (
  `playerID` INT NOT NULL AUTO_INCREMENT,
  `playerFirstName` VARCHAR(45) NULL,
  `playerLastName` VARCHAR(45) NULL,
  `dateOfBirth` DATE NULL,
  `familyID` INT NOT NULL,
  `teamID` INT NULL,
  `registrationDate` DATE NULL,
  PRIMARY KEY (`playerID`),
  CONSTRAINT `fk_player_family`
    FOREIGN KEY (`familyID`)
    REFERENCES `leaguetracker`.`family` (`familyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_team1`
    FOREIGN KEY (`teamID`)
    REFERENCES `leaguetracker`.`team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_player_family_idx` ON `leaguetracker`.`player` (`familyID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_player_team1_idx` ON `leaguetracker`.`player` (`teamID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leaguetracker`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`invoice` (
  `invoiceID` INT NOT NULL AUTO_INCREMENT,
  `familyID` INT NOT NULL,
  `paidStatus` VARCHAR(45) NULL,
  `amount` INT NULL,
  PRIMARY KEY (`invoiceID`, `familyID`),
  CONSTRAINT `fk_invoice_family1`
    FOREIGN KEY (`familyID`)
    REFERENCES `leaguetracker`.`family` (`familyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_invoice_family1_idx` ON `leaguetracker`.`invoice` (`familyID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leaguetracker`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`coach` (
  `coachID` INT NOT NULL AUTO_INCREMENT,
  `coachType` VARCHAR(45) NULL,
  `coachFirstName` VARCHAR(45) NULL,
  `coachLastName` VARCHAR(45) NULL,
  `hasClearances` VARCHAR(45) NULL,
  PRIMARY KEY (`coachID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `leaguetracker`.`coach_has_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leaguetracker`.`coach_has_team` (
  `coachID` INT NOT NULL,
  `teamID` INT NOT NULL,
  PRIMARY KEY (`coachID`, `teamID`),
  CONSTRAINT `fk_coach_has_team_coach1`
    FOREIGN KEY (`coachID`)
    REFERENCES `leaguetracker`.`coach` (`coachID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coach_has_team_team1`
    FOREIGN KEY (`teamID`)
    REFERENCES `leaguetracker`.`team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_coach_has_team_team1_idx` ON `leaguetracker`.`coach_has_team` (`teamID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_coach_has_team_coach1_idx` ON `leaguetracker`.`coach_has_team` (`coachID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

